# Site settings
title: "Yoho hamro chino"
email: "karanchetry399@gmail.com"
description: "Yo ho hamro chino pvt ltd is a cement block manufacturing company. It also deals with other concrete housing products."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
